### ISSUE TITLE
vllm version quesiton

### ISSUE THREAD

**Issue by OliverLeeXZ** [Tomorrowdawn/top_nsigma#2]
Thanks for your great work! I encounter  the problem seems like resulting in vllm version. My current vllm is 0.6.5. So which is the right vllm version used in this work?
1.Traceback (most recent call last):
  File "/home/lxz/CODE/hallucination/top_nsigma/src/vllm/test.py", line 3, in <module>
    from sampler import FacadeSampler
  File "/home/lxz/CODE/hallucination/top_nsigma/src/vllm/sampler.py", line 21, in <module>
    from vllm.sequence import (
ImportError: cannot import name 'SamplerOutput' from 'vllm.sequence' (/home/lxz/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/sequence.py)
2.Traceback (most recent call last):
  File "/home/lxz/CODE/hallucination/top_nsigma/src/vllm/test.py", line 3, in <module>
    from sampler import FacadeSampler
  File "/home/lxz/CODE/hallucination/top_nsigma/src/vllm/sampler.py", line 16, in <module>
    from vllm.model_executor.layers.ops.sample import sample as sample_triton
ModuleNotFoundError: No module named 'vllm.model_executor.layers.ops'

**Comment by Tomorrowdawn** [comment]
Hello now I upload the code in `dev` branch. The vLLM version is `0.5.5`. I guess they are planning to release a 1.0 version, so there are many breaking changes.
